### ISSUE TITLE
Merge some of the menu items into Retail and create common segmentedbutton for them

### ISSUE THREAD

**Issue by voitakn** [voitakn/voita-erp-front#2]
Нужно соединить в общее главное меню Retail следующие пункты:
Sellings, 
POS, 
Cash registers, 
Refunds, 
Price monitor
Эти меню сделать как кнопки segmentedbutton над всеми этими модулями,
чтобы при активном компоненте выделялся нужный пункт в кнопке
У всех этих страниц общий заголовок Retail (SALES, POS, CHECKOUTS, REFUNDS, PRICE STICKERS)

**Comment by EKarakay** [comment]
Merge some of the menu items into Retail and create common segmentedbutton for them

**Comment by EKarakay** [comment]
Merge some of the menu items into Retail and create common segmentedbutton for them
